//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hbb_ges.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hbb_ges.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnaSayfa.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        public static string Galeri {
            get {
                return ResourceManager.GetString("Galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GES.
        /// </summary>
        public static string GES {
            get {
                return ResourceManager.GetString("GES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        public static string TR
        {
            get
            {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        public static string tanitim
        {
            get
            {
                return ResourceManager.GetString("tanitim", resourceCulture);
            }
        }
        public static string faydalar
        {
            get
            {
                return ResourceManager.GetString("faydalar", resourceCulture);
            }
        }
        public static string adres
        {
            get
            {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        public static string kaydet
        {
            get
            {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        public static string Mesaj
        {
            get
            {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }public static string Konu
        {
            get
            {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }public static string email
        {
            get
            {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }public static string Adsoyad
        {
            get
            {
                return ResourceManager.GetString("Adsoyad", resourceCulture);
            }
        }public static string footer
        {
            get
            {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
    }
}
